# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 19:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20170125_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='dateshow',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='timeshow',
            field=models.TimeField(),
        ),
    ]
